### ISSUE TITLE
c0/v0_Consist (No) - c0/v1_Consist (No)

### ISSUE THREAD

**Issue by nenominal** [thomas-krenn/check_lsi_raid#19]
Hi,

I'm not sure if this is really a issue but I have two identical Centos 7.5 servers with LSI 2108 raid controllers.
On one server I'm getting 

Warning sensors:- c0/v0_Consist (No) - c0/v1_Consist (No)

I'm not pretty sure what it really means, I've checked with storecli and megaraid storage manager and I can not find any errors.

Any input will be appreciated.

Thanks.

**Comment by gschoenberger** [comment]
Normally "Consist" means, that a consistency check was executed for a virtual drive (LD) and did not return an error.
You can check with "storcli /c0 show cc" if consistency checks are enabled for your controller.
The sensor "c0/v0_Consist" states that "Consist" for "v0" is current set to "No", whereas the plugin expects "Yes".

**Comment by nenominal** [comment]
Hi,

that's very odd as both servers seems to have identical set-up
This is a print-screen with configs for both servers [](https://i.imgur.com/sL76sRA.png)

**Comment by nenominal** [comment]
Ok, I got it. For an unknown reason, even though the volumes were working as expected for very long time, the controller didn't find them as initialized.

DG/VD TYPE   State Access Consist Cache Cac sCC       Size Name 
----------------------------------------------------------------
0/0   RAID1  Optl  RW     **No**      RWTD  -   ON  464.729 GB      
1/1   RAID10 Optl  RW     **No**      RWTD  -   ON    3.635 TB      

The consistency **NO** , in this case, it's about uninitialized volume.

storcli /c0/vx  start init full force did the trick.

**Comment by aj-gh** [comment]
You can also trigger a consistency check instead of doing a full initialization:
storcli /c0 set cc=conc starttime=2018/05/29 14

Status can be displayed with "storcli /c0 show cc", rate with "storcli /c0 show ccrate".
This rate can be modified with "storcli /c0 set ccrate=xx".

When the check is finished and was previously disabled you can disable it again, otherwise it will run automatically after a while (e.g. each month): "storcli /c0 set cc=off"

All in all I think "consist no" should be ignored if consistency checking is not enabled.

**Comment by kirkog86** [comment]
Very usable!!! Thanks.
